version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    command: --serviceExecutor adaptive
    expose:
      - 27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
  nodejs:
    image: node:12.16.3-alpine
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    working_dir: /root/app
    volumes:
      - ./:/root/app:cached
    depends_on:
      - mongo
